import * as React from 'react'
import { useLyricsEditingStore } from '@/stores/lyricsEditingStore'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ChevronDown, ChevronUp, Eye, EyeOff } from 'lucide-react'
import { cn } from '@/lib/utils'

export const LyricsPreview: React.FC = () => {
  const { originalLyrics } = useLyricsEditingStore()
  const [isVisible, setIsVisible] = React.useState(false)
  
  // Generate unique IDs for ARIA attributes
  const titleId = 'lyrics-preview-title'
  const contentId = 'lyrics-preview-content'
  const descriptionId = 'lyrics-preview-description'
  
  // Don't render if no original lyrics
  if (!originalLyrics || originalLyrics.trim().length === 0) {
    return null
  }
  
  const toggleVisibility = () => {
    setIsVisible(!isVisible)
  }
  
  return (
    <Card 
      className="border-dashed"
      role="region"
      aria-labelledby={titleId}
    >
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle 
            id={titleId}
            className="text-sm font-medium flex items-center gap-2"
          >
            <span aria-hidden="true">
              {isVisible ? (
                <Eye className="h-4 w-4" />
              ) : (
                <EyeOff className="h-4 w-4" />
              )}
            </span>
            Original AI-Generated Lyrics
          </CardTitle>
          <Button
            variant="ghost"
            size="sm"
            onClick={toggleVisibility}
            className="h-8 w-8 p-0 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
            aria-expanded={isVisible}
            aria-controls={contentId}
            aria-label={isVisible ? 'Hide original lyrics' : 'Show original lyrics'}
          >
            <span aria-hidden="true">
              {isVisible ? (
                <ChevronUp className="h-4 w-4" />
              ) : (
                <ChevronDown className="h-4 w-4" />
              )}
            </span>
          </Button>
        </div>
      </CardHeader>
      
      {isVisible && (
        <CardContent id={contentId}>
          <div 
            className={cn(
              "p-4 bg-muted/50 rounded-md",
              "max-h-[400px] overflow-y-auto",
              "whitespace-pre-wrap font-mono text-sm",
              "focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none"
            )}
            role="region"
            aria-label="Original AI-generated lyrics content"
          >
            {originalLyrics}
          </div>
          <p 
            id={descriptionId}
            className="text-xs text-muted-foreground mt-2"
          >
            This is the original version generated by AI. You can compare it with your edits above.
          </p>
        </CardContent>
      )}
    </Card>
  )
}
